# Basic
title: Airde Craft
subtitle: ä¸ªäººç«™
description: Welcome to Airde Craft
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Airde Craft
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ç‚¹å‡»è¿›å…¥
url: "https://airdecraft.github.io/"

# Comment
comment:
    # disqus: leopard
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    # weibo: 5366874726 
    github: airdecraft
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: 465516192@qq.com



# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Airde Craft ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: ä¿¡æ¯å…¬å¸ƒ, description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾åˆ†ç±», description: tags, url: '/tags'}      
    - {title: å›¢é˜Ÿä¿¡æ¯, description: about, url: '/about'}      

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


